name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: The number of the PR that is being deployed
        required: false
        type: string
      ref:
        description: The branch that is being deployed
        required: false
        default: main
        type: string
  push:
    branches:
      - main

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  publish:
    name: Publish Next to NPM
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Kings-World'
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - cron
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Packages
        run: yarn build

      - name: Bump Versions and Publish
        working-directory: packages/${{ matrix.package }}
        run: |
          # Resolve the tag to be used. "next" for push events, "pr-{prNumber}" for dispatch events.
          TAG=$([[ ${{ github.event_name }} == 'push' ]] && echo 'next' || echo "pr-${PR_NUMBER}")

          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          echo "tag = ${TAG}"
          echo "pr number = ${PR_NUMBER}"
          echo "version = ${TAG}.$(git rev-parse --verify --short HEAD)"

          yarn bump --preid "${TAG}.$(git rev-parse --verify --short HEAD)" --skip-changelog

          yarn npm publish --tag ${TAG}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.prNumber }}
