name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Linter
        run: yarn lint --fix=false

  typechecking:
    name: Typechecking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # this is the same as the tsc problem matcher from actions/setup-node
      # the only difference being the "Error: " prefix being added to the regex
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/turbo-tsc.json"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Typecheck
        run: yarn typecheck

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Prettier
        run: yarn prettier --check .

  commitlint:
    name: Commit Message Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --immutable

      # https://commitlint.js.org/guides/ci-setup#github-actions
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: yarn commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
